name: Hardhat CI on main branch

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install
      - run: npx --version

      - run: npx hardhat typechain
        env:
          INFURA_MAINNET: ${{ secrets.INFURA_MAINNET }}
      - run: echo "🎉 Hardhat Typechain passed."

      - run: npx hardhat test
        env:
          INFURA_MAINNET: ${{ secrets.INFURA_MAINNET }}
      - run: echo "🎉 Hardhat Test passed."

      - run: npx hardhat coverage
        env:
          INFURA_MAINNET: ${{ secrets.INFURA_MAINNET }}
